version: '3.9'

services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=bot"

  app:
    build: .
    restart: always
    env_file: env/docker.env
    tty: true
    depends_on:
      - mariadb
